//'use client'
import React from 'react';
import { useState } from "react";
import styles from '../styles/header.module.css';
import { MongoDBLogoMark } from '@leafygreen-ui/logo';
import { H2, Body } from '@leafygreen-ui/typography';
import InfoWizard from "./InfoWizard/InfoWizard";

function Header() {
  const [openHelpModal, setOpenHelpModal] = useState(false);

  return (
    <div className={styles["layout-header"]}>
      <div className={styles["logo-container"]}>
        <MongoDBLogoMark />
      </div>
      <div className={styles["title-container"]}>
        <H2>Business Loan Risk Assessor </H2>
      </div>

      <div className={styles["wizard-container"]}>
        <InfoWizard
          open={openHelpModal}
          setOpen={setOpenHelpModal}
          tooltipText="Tell me more!"
          iconGlyph="Wizard"
          sections={[
            {
              heading: "Instructions and Talk Track",
              content: [
                {
                  heading: "What is the Purpose of this Demo?",
                  body: "This demo is to illustrate how GenAI can potentially help a borrower or a loan officer to assess the risk of a business loan for starting a business at a physical location. As part of such business loan assessment, it is a common practice for lenders to also assess the physical climate risks (such as flood risks) that can impact the borrower income and repayability. In our solution library, we have explained that without the use of RAG, LLMs show hallucination when trying to perform ood risk assessments.",
                },
                {
                  heading: "How to Demo",
                  body: [
                    "Type in a location at the location search bar or simply select on the example locations provided in the drop down list",
                    "Type in a business plan or ask the system to general the business plan by clicking on the “Example” button on lower right of the text entry box",
                    "Click the “Submit”",
                    "Wait and scroll down to read for the “Assessor’s response” which is generated by GenAI.",
                    "Explain that GenAI can be used to perform loan risk assessment and including climate risk such as flood risk using RAG leveraging on MongoDB Geospatial capabilities.",
                    "Click on the “pin” icon on the right side of the location search bar to then reveal where flood locations are on the map from the previous years marked by different color. The map will also show a 5km radius from the location of the business selected. This demonstrates other ways of how geospatial analytics can be used to visualize the flood location and in turn location-related data points.",
                  ],
                },
              ],
            },
            {
              heading: "Behind the Scenes",
              content: [
                {
                  heading: "Data Flow",
                  body: "",
                },
                {
                  image: {
                    src: "./info.png",
                    alt: "Architecture",
                  },
                },
              ],
            },
            {
              heading: "Why MongoDB?",
              content: [
                {
                  heading: "Flexible Data Model",
                  body: "MongoDB's document-based data model offers great flexibility for handling diverse and dynamic datasets, which are common in AI and machine learning applications. This enables you to store complex, varied data crucial for assessing loan risks, such as financial records, market data, and customer profiles, without the need for a predefined schema.",
                },
                {
                  heading: "Efficient Querying",
                  body: "MongoDB provides powerful indexing and aggregation features that can efficiently handle complex queries and large datasets, which are typical in risk assessment scenarios. This can enhance the performance of AI models that sift through large volumes of data to predict loan risks.",
                },
                {
                  heading: "Easy Integration",
                  body: "MongoDB integrates well with various data processing and machine learning frameworks. This makes it easier to incorporate generative AI models into the workflow, facilitating an end-to-end solution.",
                },
              ],
            },
          ]}
        />
      </div>
    </div>

  );
}

export default Header;

